version: '3.6'

services:

  redis:
    image: "redis:alpine"
  web:
    build: .
    restart: always
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    container_name: Atlan
    environment:
      - ENVIRONMENT=production
    volumes:
      - .:/Atlan
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A Collect worker -l info
    volumes:
      - .:/Atlan
    depends_on:
      - redis