version: '3.6'

services:

  redis:
    image: "redis:alpine"
  web:
    build: .
    restart: always
    environment:
      DEBUG: 1
      ALLOWED_HOSTS: "*"
      SECRET_KEY: "secretkey1"
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8080 Collect.wsgi"
    container_name: Atlan
    ports:
      - "8080:8080"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A Collect worker -l info
    depends_on:
      - redis