# Generated by Django 2.2.4 on 2019-08-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExampleTasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdata',
            old_name='task_id',
            new_name='task',
        ),
    ]
