# Generated by Django 2.2.4 on 2019-08-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExampleTasks', '0002_auto_20190818_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
