# Generated by Django 2.2.4 on 2019-08-20 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExampleTasks', '0003_task_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
